# Generated by Django 3.0.6 on 2020-05-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
